# Website deployment script for gitlab
# @author Denis Zholob (deniszholob.com)
#
# Runs the build script
# ====================================== #

image: node:latest # Building with node js

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
    paths:
        - node_modules/


pages:
    stage: deploy
    script:
        - echo 'Building app...'
        - sh ./buildscripts/build.sh # Generates the public folder with built angular app
        - echo 'Deploying app...'
    artifacts:
        paths:
            - public # Generated/Compiled code
    only:
        - master
